name: Profile Status

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROJECTS: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          COMMIT_MESSAGE: Updated the Readme
